fix(soap): Encode keytab path to bytes for GSSAPI store
The gssapi store requires byte strings.

__main__:ERROR:Traceback (most recent call last):
  File "/usr/libexec/certmonger/cepces-submit", line 63, in main
    config = Configuration.load(global_overrides=global_overrides,
  File "/usr/lib/python3.9/site-packages/cepces/config.py", line 207, in load
    return Configuration.from_parser(config)
  File "/usr/lib/python3.9/site-packages/cepces/config.py", line 272, in from_parser
    authn.handle(),\n  File "/usr/lib/python3.9/site-packages/cepces/auth.py", line 116, in handle
    auth = SOAPAuth.TransportGSSAPIAuthentication(
  File "/usr/lib/python3.9/site-packages/cepces/soap/auth.py", line 104, in __init__
    gssapi_cred = self._init_ccache()
  File "/usr/lib/python3.9/site-packages/cepces/soap/auth.py", line 126, in _init_ccache
    gssapi_cred = gssapi.raw.acquire_cred_from(
  File "gssapi/raw/ext_cred_store.pyx", line 158, in gssapi.raw.ext_cred_store.acquire_cred_from
  File "gssapi/raw/ext_cred_store.pyx", line 86, in gssapi.raw.ext_cred_store.c_create_key_value_set
TypeError: expected bytes, str found